In [1]:
run main.py

/home/M2015eliu/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/gensim/utils.py:1015: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 2 failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 4007)


Loading Word2Vec
NO Training. Load the existed model: weights/201611232246_e10_1k1k.p
Evaluate the model using fast estimation...
Finish preparing the data!
Finished embedding,start projecting...
conducting the 0 projection
conducting the 1 projection
conducting the 2 projection
conducting the 3 projection
conducting the 4 projection
conducting the 5 projection
conducting the 6 projection
conducting the 7 projection
conducting the 8 projection
conducting the 9 projection
conducting the 10 projection
conducting the 11 projection
conducting the 12 projection
conducting the 13 projection
conducting the 14 projection
conducting the 15 projection
conducting the 16 projection
conducting the 17 projection
conducting the 18 projection
conducting the 19 projection
conducting the 20 projection
conducting the 21 projection
conducting the 22 projection
conducting the 23 projection
conducting the 24 projection
conducting the 25 projection
conducting the 26 projection
conducting the 27 projection
co

KeyboardInterrupt: 

In [5]:
import pickle
if True:
	with open("train_1.p", 'wb') as handle:
	    pickle.dump(train_1, handle)
	with open("train_2.p", 'wb') as handle:
	    pickle.dump(train_2, handle)
	with open("test_1.p", 'wb') as handle:
	    pickle.dump(test_1, handle)
	with open("test_2.p", 'wb') as handle:
	    pickle.dump(test_2, handle)
	with open("df_train_1.p", 'wb') as handle:
	    pickle.dump(df_train_1, handle)
	with open("df_test_1.p", 'wb') as handle:
	    pickle.dump(df_test_1, handle)

In [ ]:
list1, list2 = sls.evaluate2(train_1)

NameError: name 'use_noise' is not defined

In [12]:
sls.evaluate2(train_1)

KeyboardInterrupt: 

In [13]:
train_1

[['5 2 9 6 6 6 6 2 6 6',
  '1 8 2 3 9 7 2 9 7 2 9 7 2 9 7 2 8 2 9 7 2 9 7 2',
  5.0],
 ['2 6 2 2 2 1 2 2 5 6 2 2 2 2 10 8 5 6 1 8 2 5 2 2 2 2 2 2 2 2 2 1 9 2 7 10 2 10 2 6 2 2 2 5 7 2 2 2 2 2 2 2 2 7 7 2 7 1 7 2 7 1 2 2 4 5 5 2 2 8 10 7 2 7 2 2 5 6 2 6 2 6 5 5 2 2 2 4 5 6 6 5 2 5 2 2 5 4 6 6 5 6 6 10 10 2 2 2 7 2 2 2 2 2 7 2 2 4 5 8 2 2 2 5 5 5 2 7 2 2 2 2 2 5 2 2 7 6 2 7 10 5 8 6 5 1 4 6 5 2 2 2 5 6 2 2 2 2 4 5 6 1 2 2 2 4 1 2 2 2 2 1 7 6 6 5 10 2 2',
  '8 2 9 7 2 8 2 8 2 8 2 6 8 2 8 2 1 9 7 2 8 2 8 2 8 2 8 2 4 4 1 9 7 2 6 4 8 2 1 8 2 8 2 8 2 8 2 8 2 8 2 8 2 8 2 8 2 6 3 8 2 10 3 4 8 2 4 8 2 9 7 2 8 2 8 2 8 2 1 10 3 8 2 8 2 8 2 8 2 8 2 8 2 8 2 8 2 10 3 10 3 8 2 10 3 6 10 3 8 2 10 3 6 8 2 8 2 10 1 1 8 2 8 2 4 4 10 3 8 2 10 3 8 2 8 2 1 9 7 2 8 2 9 7 2 8 2 9 7 2 1 1 8 2 8 2 8 2 10 1 9 7 2 9 7 2 1 8 2 1 8 2 8 2 1 10 9 7 2 9 7 2 1 9 7 2 9 7 2 4 4 8 2 8 2 8 2 10 3 8 2 8 2 8 2 8 2 8 2 10 3 8 2 8 2 10 1 4 8 2 8 2 8 2 1 1 1 8 2 10 3 8 2 8 2 8 2 8 2 8 2 1 8 2 8 2 10 3 9 7 2 8 2 10 3 4 1 4 9 7 2 

In [2]:
rank_results_tr = sls.evaluate(train_1)

the round 0 rank: 9.0
the round 1 rank: 4.0
the round 2 rank: 1.0
the round 3 rank: 32.5
the round 4 rank: 29.5
the round 5 rank: 1.0
the round 6 rank: 1.0
the round 7 rank: 2.0
the round 8 rank: 51.0
the round 9 rank: 13.0
the round 10 rank: 9.5
the round 11 rank: 1.0
the round 12 rank: 4.0
the round 13 rank: 3.0
the round 14 rank: 3.5
the round 15 rank: 4.0
the round 16 rank: 4.0
the round 17 rank: 7.0
the round 18 rank: 1.5
the round 19 rank: 3.0
the round 20 rank: 1.0
the round 21 rank: 157.5
the round 22 rank: 12.0
the round 23 rank: 1.0
the round 24 rank: 5.0
the round 25 rank: 60.0
the round 26 rank: 3.0
the round 27 rank: 17.0
the round 28 rank: 87.0
the round 29 rank: 2.0
the round 30 rank: 4.0
the round 31 rank: 2.0
the round 32 rank: 3.0
the round 33 rank: 9.0
the round 34 rank: 8.5
the round 35 rank: 1.0
the round 36 rank: 1.0


KeyboardInterrupt: 

In [1]:
run main.py

/home/M2015eliu/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/gensim/utils.py:1015: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 2 failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 4007)


NO Training. Load the existed model: weights/201611232246_e10_1k1k.p
Evaluate the model using fast estimation...
Finish preparing the data!
Finished embedding,start projecting...


In [7]:
projection1_train.shape

(999, 50)

In [8]:
projection2_train.shape

(999, 50)

In [10]:
projection1_test, projection2_test = sls.evaluate2(test_1)

Finish preparing the data!
Finished embedding,start projecting...


In [11]:
projection1_test

array([[-0.5775218 ,  0.28319162,  0.21150576, ...,  0.31114298,
         0.58363318, -0.3614282 ],
       [-0.57752252,  0.28318372,  0.2115099 , ...,  0.31114441,
         0.5836342 , -0.36143059],
       [-0.57639933,  0.27161601,  0.20511793, ...,  0.31066808,
         0.58341449, -0.36107928],
       ..., 
       [-0.57723743,  0.28382131,  0.21006688, ...,  0.31053504,
         0.58313376, -0.36064696],
       [-0.57748681,  0.28374028,  0.2112993 , ...,  0.31104758,
         0.58355534, -0.36128694],
       [-0.57747674,  0.28280303,  0.21124867, ...,  0.31107554,
         0.58358651, -0.36132905]], dtype=float32)

In [17]:
train_1[0]

['5 2 9 6 6 6 6 2 6 6', '1 8 2 3 9 7 2 9 7 2 9 7 2 9 7 2 8 2 9 7 2 9 7 2', 5.0]

In [30]:
a = [1,2,3]

In [31]:
b = []

In [34]:
b += a

In [35]:
b

[1, 2, 3, 1, 2, 3]

In [1]:
run main.py

/home/M2015eliu/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/gensim/utils.py:1015: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 2 failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 4007)


NO Training. Load the existed model: weights/201611232246_e10_1k1k.p
Evaluate the model using fast estimation...
998001 998001
Finish data extension


KeyboardInterrupt: 

In [5]:
a= [[1],[1],[1],[1],]

In [6]:
b = []

In [10]:
b += a

In [11]:
b

[[1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1], [1]]

In [7]:
tr = []

37962

In [50]:
sls.evaluate2(train_1)

Finish preparing the data!
Finished embedding,start projecting...


RuntimeError: Cuda error: GpuElemwise node_6ef5f7745f479bcd75a837a5e89a3110_0 Sub: out of memory.
    n_blocks=30 threads_per_block=256
   Call: kernel_Sub_node_6ef5f7745f479bcd75a837a5e89a3110_0_Ccontiguous<<<n_blocks, threads_per_block>>>(numEls, i0_data, i1_data, o0_data)

Apply node that caused the error: GpuElemwise{sub,no_inplace}(CudaNdarrayConstant{[[[ 1.]]]}, GpuDimShuffle{0,1,x}.0)
Toposort index: 55
Inputs types: [CudaNdarrayType(float32, (True, True, True)), CudaNdarrayType(float32, (False, False, True))]
Inputs shapes: [(1, 1, 1), (1354, 999, 1)]
Inputs strides: [(0, 0, 0), (999, 1, 0)]
Inputs values: [CudaNdarray([[[ 1.]]]), 'not shown']
Outputs clients: [[forall_inplace,gpu,1lstm1__layers}(Elemwise{maximum,no_inplace}.0, GpuDimShuffle{0,1,x}.0, GpuElemwise{sub,no_inplace}.0, GpuSubtensor{int64:int64:int8}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuDimShuffle{x,0}.0, GpuDimShuffle{1,0}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

In [1]:
run main.py

/home/M2015eliu/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/gensim/utils.py:1015: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 2 failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 4007)


NO Training. Load the existed model: weights/201611232246_e10_1k1k.p


In [5]:
tr = []
for i in range(5):
    tr += train_1
len(tr)

4995

In [4]:
projection1_tr, projection2_tr = sls.evaluate(tr)

RuntimeError: Cuda error: GpuElemwise node_6ef5f7745f479bcd75a837a5e89a3110_0 Sub: out of memory.
    n_blocks=30 threads_per_block=256
   Call: kernel_Sub_node_6ef5f7745f479bcd75a837a5e89a3110_0_Ccontiguous<<<n_blocks, threads_per_block>>>(numEls, i0_data, i1_data, o0_data)

Apply node that caused the error: GpuElemwise{sub,no_inplace}(CudaNdarrayConstant{[[[ 1.]]]}, GpuDimShuffle{0,1,x}.0)
Toposort index: 110
Inputs types: [CudaNdarrayType(float32, (True, True, True)), CudaNdarrayType(float32, (False, False, True))]
Inputs shapes: [(1, 1, 1), (1354, 19980, 1)]
Inputs strides: [(0, 0, 0), (19980, 1, 0)]
Inputs values: [CudaNdarray([[[ 1.]]]), 'not shown']
Outputs clients: [[forall_inplace,gpu,2lstm1__layers}(Elemwise{maximum,no_inplace}.0, GpuDimShuffle{0,1,x}.0, GpuElemwise{sub,no_inplace}.0, GpuSubtensor{int64:int64:int8}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuIncSubtensor{InplaceSet;:int64:}.0, GpuDimShuffle{x,0}.0, GpuDimShuffle{1,0}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

In [6]:
projection1_tr, projection2_tr = sls.evaluate2(tr)

Finish preparing the data!
Finished embedding,start projecting...


In [9]:
projection1_tr[0]

array([-0.57329977,  0.00860893,  0.0496361 , -0.32185242,  0.31147963,
       -0.3696304 ,  0.35420561,  0.31866023,  0.29494464,  0.47207081,
        0.57274902, -0.26168406, -0.45802501,  0.23758702, -0.47979718,
        0.00994731,  0.40486962, -0.64692128, -0.25206771,  0.5175904 ,
       -0.13293587,  0.54621744, -0.51533931, -0.57018924,  0.51342422,
       -0.46902913,  0.59191883, -0.5999499 , -0.5047102 ,  0.1640372 ,
       -0.09745441, -0.3871839 ,  0.65192932,  0.54712337,  0.60808003,
       -0.27279592,  0.62118435,  0.0139573 , -0.57140243, -0.51683432,
       -0.04979859,  0.03414029,  0.36952665,  0.2911182 , -0.39222816,
        0.30849114,  0.66221207,  0.29250827,  0.57070887, -0.38285986], dtype=float32)

In [11]:
projection2_tr[0]

array([-0.57295495,  0.08650167,  0.11346965, -0.34865054,  0.32038087,
       -0.37811747,  0.35411647,  0.31807742,  0.29294685,  0.47292489,
        0.56928068, -0.28699967, -0.46663886,  0.27758682, -0.48221228,
       -0.0352697 ,  0.40578926, -0.64621025, -0.25636882,  0.51553804,
       -0.22753131,  0.54562753, -0.52351922, -0.57354563,  0.50851339,
       -0.4828375 ,  0.59900683, -0.62529701, -0.5131439 ,  0.21122235,
       -0.0860132 , -0.39460325,  0.65273708,  0.55617535,  0.61165744,
       -0.28508002,  0.62482363,  0.04324748, -0.56633079, -0.51235151,
        0.05299769,  0.08560295,  0.36473307,  0.42714673, -0.39026606,
        0.31066132,  0.67234856,  0.28869691,  0.56605852, -0.38521916], dtype=float32)

In [12]:
projection1_tr

array([[-0.57329977,  0.00860893,  0.0496361 , ...,  0.29250827,
         0.57070887, -0.38285986],
       [-0.55642074,  0.06584875,  0.08626437, ...,  0.29084891,
         0.57342583, -0.39360806],
       [-0.57176948,  0.24665451,  0.15039735, ...,  0.2988106 ,
         0.57245773, -0.38821188],
       ..., 
       [-0.57585251,  0.29241428,  0.18565199, ...,  0.28898278,
         0.56475097, -0.3874138 ],
       [-0.53362215,  0.26396638,  0.17549339, ...,  0.320793  ,
         0.59448326, -0.35905084],
       [-0.5431295 ,  0.26760367,  0.1879721 , ...,  0.31911686,
         0.58956498, -0.35463664]], dtype=float32)

In [22]:
np.linalg.norm(projection1_tr[10] - projection1_tr[100], 1)

1.1669137

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.], dtype=float32)

In [42]:
diff = np.linalg.norm(projection1_tr[1] - projection2_tr[1], 1)
sim = np.exp(-diff)
print sim

0.63014


In [43]:
diff = np.linalg.norm(projection1_tr - projection2_tr, 1, axis=1)
sim = np.exp(-diff)
len(diff)

4995

In [67]:
sim[0]

0.38925272

In [45]:
type(projection1_tr)

numpy.ndarray

In [46]:
projection1_tr.shape

(4995, 50)

In [50]:
a = np.array([1,2,3])

In [49]:
b = np.array([1])

In [51]:
a

array([1, 2, 3])

In [52]:
b

array([1])

In [53]:
a + b

array([2, 3, 4])

In [54]:
def cal_similarity(a, b):
	diff = np.linalg.norm(a - b, 1, axis=1)
	sim = np.exp(-diff)
	# len(diff)
	return sim

def find_ranking(projection1, projection2):
	for proj1 in projection1:
		cal_similarity(proj1, projection1)


In [55]:
find_ranking(projection1_tr, projection2_tr)

In [72]:
cal_similarity(projection1_tr[0], projection2_tr)

array([ 0.38925272,  0.24512236,  0.1594272 , ...,  0.12098336,
        0.05521592,  0.02769872], dtype=float32)

In [63]:
r[1]

0.24512236

In [65]:
cal_similarity(projection1_tr, projection2_tr)

array([ 0.38925272,  0.63013977,  0.78736782, ...,  0.83638781,
        0.83885843,  0.86947155], dtype=float32)

In [69]:
projection1_tr[0].shape

(50,)

In [70]:
projection2_tr.shape

(4995, 50)

In [73]:
# 使用新的方法预测相似度为0.630， 对于df[1]数据来说 【正确】
cal_similarity(projection1_tr[1], projection2_tr)

array([ 0.22727746,  0.63013977,  0.17849362, ...,  0.07390206,
        0.02617434,  0.01107444], dtype=float32)

In [80]:
# 使用传统的方法预测相似度为 0.630 对 df[1]数据来说 【正确】
sls.predict_similarity(df_train_1.ix[1].xa, df_train_1.ix[1].xb)

array([ 0.63013977], dtype=float32)

In [93]:
def cal_similarity(a, b):
	diff = np.linalg.norm(a - b, 1, axis=1)
	sim = np.exp(-diff)
	# len(diff)
	return sim

def find_ranking(projection1, projection2):
	sim_results = []
	for proj1 in projection1:
		sim = cal_similarity(proj1, projection2)
		sim_results.append(sim)
	return sim_results

In [95]:
re = find_ranking(projection1_tr, projection2_tr)

In [102]:
re[1003]

array([ 0.12206398,  0.04660977,  0.15984976, ...,  0.37773153,
        0.10056104,  0.17697971], dtype=float32)

In [103]:
re1 = cal_similarity(projection1_tr[1003], projection2_tr)
re1

array([ 0.12206398,  0.04660977,  0.15984976, ...,  0.37773153,
        0.10056104,  0.17697971], dtype=float32)

In [90]:
np.shape(re[0])

(4995,)

In [91]:
np.shape(re1)

(4995,)

In [104]:
np.shape(re)

(4995, 4995)

In [105]:
df_re = pd.DataFrame(re)

In [106]:
df_re

0         1         2         3         4         5         6     \
0     0.389253  0.245122  0.159427  0.072825  0.073285  0.164508  0.105434   
1     0.227277  0.630140  0.178494  0.035580  0.036057  0.125299  0.024436   
2     0.228736  0.221406  0.787368  0.235410  0.238389  0.407064  0.022160   
3     0.119173  0.045105  0.154857  0.802559  0.791971  0.220941  0.012703   
4     0.122064  0.046610  0.159850  0.811678  0.813712  0.228230  0.012809   
5     0.322137  0.167731  0.314320  0.310628  0.310545  0.824841  0.019426   
6     0.043679  0.027758  0.023807  0.013219  0.013304  0.018909  0.788977   
7     0.060063  0.025477  0.072938  0.190156  0.192222  0.109496  0.013816   
8     0.034207  0.014323  0.040504  0.128298  0.126562  0.062147  0.010696   
9     0.318989  0.150320  0.273039  0.352405  0.357115  0.638017  0.020169   
10    0.304475  0.128933  0.257711  0.430849  0.436457  0.550384  0.019707   
11    0.413506  0.155899  0.211776  0.311117  0.313259  0.425662  0.029023   
12    0.328464  0.481005  0.435197  0.105967  0.107422  0.188323  0.033896   
13    0.331905  0.475949  0.475169  0.112859  0.114356  0.405246  0.023725   
14    0.068670  0.031041  0.085136  0.164184  0.166180  0.110496  0.014720   
15    0.068011  0.028477  0.081195  0.177256  0.178494  0.122720  0.015963   
16    0.269828  0.139840  0.157383  0.093487  0.094107  0.113901  0.124987   
17    0.134334  0.055116  0.188115  0.748264  0.757365  0.258573  0.012941   
18    0.128180  0.062565  0.222737  0.319200  0.323276  0.232988  0.016634   
19    0.000055  0.000042  0.000028  0.000016  0.000016  0.000024  0.001049   
20    0.080755  0.029943  0.102814  0.533447  0.526520  0.146742  0.011340   
21    0.063096  0.025368  0.090142  0.413171  0.410154  0.118121  0.010356   
22    0.341508  0.560506  0.442409  0.091549  0.092763  0.326912  0.026292   
23    0.065141  0.025519  0.090438  0.404517  0.404549  0.118164  0.010785   
24    0.488976  0.553430  0.288066  0.089745  0.090948  0.311399  0.030396   
25    0.097067  0.036085  0.121369  0.623910  0.616135  0.176432  0.012941   
26    0.040190  0.016828  0.049192  0.192812  0.193756  0.073016  0.009636   
27    0.288924  0.364400  0.571061  0.149091  0.151077  0.278398  0.025336   
28    0.150656  0.060909  0.208419  0.765260  0.775610  0.283941  0.014370   
29    0.127445  0.047716  0.164843  0.804919  0.794863  0.231677  0.014033   
...        ...       ...       ...       ...       ...       ...       ...   
4965  0.315587  0.168981  0.300963  0.325298  0.329654  0.566701  0.018632   
4966  0.052620  0.020608  0.072994  0.318575  0.314477  0.095259  0.012152   
4967  0.303011  0.113439  0.254153  0.431055  0.436253  0.284406  0.030654   
4968  0.427814  0.163375  0.140478  0.132166  0.133034  0.175186  0.077666   
4969  0.127842  0.053506  0.157554  0.326140  0.330294  0.157764  0.019378   
4970  0.050216  0.019666  0.069558  0.304035  0.304215  0.088827  0.010082   
4971  0.209105  0.617992  0.186560  0.036770  0.037258  0.130443  0.023195   
4972  0.100090  0.066117  0.113335  0.059433  0.060053  0.075724  0.037716   
4973  0.099636  0.036812  0.082757  0.369179  0.364446  0.181198  0.009022   
4974  0.097840  0.036153  0.081317  0.362678  0.358029  0.177883  0.008981   
4975  0.239907  0.091166  0.190159  0.564045  0.567754  0.435495  0.017970   
4976  0.040857  0.017107  0.048513  0.177348  0.174919  0.073320  0.012323   
4977  0.053389  0.020909  0.074048  0.323176  0.319019  0.096642  0.012261   
4978  0.089363  0.232262  0.073070  0.014228  0.014416  0.049663  0.015416   
4979  0.040715  0.017048  0.048338  0.176673  0.174253  0.073054  0.012293   
4980  0.050038  0.020952  0.058947  0.144007  0.142642  0.086326  0.015793   
4981  0.090629  0.038625  0.084082  0.106672  0.107785  0.086438  0.024018   
4982  0.048780  0.029352  0.077349  0.104024  0.103165  0.087124  0.022164   
4983  0.143051  0.393378  0.114717  0.022502  0.022800  0.079212  0.018353   
4984  0.047699  0.028797  0.0757

In [132]:
def cal_similarity(a, b):
	diff = np.linalg.norm(a - b, 1, axis=1)
	sim = np.exp(-diff)
	# len(diff)
	return sim

def find_ranking(projection1, projection2):
	sim_results = []
	rank_results = []
	for i, proj1 in enumerate(projection1):
		sim = cal_similarity(proj1, projection2)
		rank = pd.Series(sim).rank(ascending = False)[i]
		sim_results.append(sim)
		rank_results.append(rank)
	return sim_results, rank_results


In [108]:
	projection1_train, projection2_train = sls.evaluate2(train_1)
	projection1_test, projection2_test = sls.evaluate2(test_1)

Finish preparing the data!
Finished embedding,start projecting...
Finish preparing the data!
Finished embedding,start projecting...


In [134]:
sim_results, rank_results = find_ranking(projection1_tr, projection2_tr)

In [129]:
print len(sim_results), len(rank_results)

4995 4995


In [130]:
sim_results[0]

array([ 0.38925272,  0.24512236,  0.1594272 , ...,  0.12098336,
        0.05521592,  0.02769872], dtype=float32)

In [135]:
rank_results

[43.0,
 18.0,
 3.0,
 160.5,
 145.5,
 3.0,
 3.0,
 8.0,
 253.0,
 63.0,
 45.5,
 3.0,
 18.0,
 13.0,
 15.5,
 18.0,
 18.0,
 33.0,
 5.5,
 13.0,
 3.0,
 785.5,
 58.0,
 3.0,
 23.0,
 298.0,
 13.0,
 83.0,
 433.0,
 8.0,
 18.0,
 8.0,
 13.0,
 43.0,
 40.5,
 3.0,
 3.0,
 18.0,
 13.0,
 3.0,
 3.0,
 103.0,
 3.0,
 3.0,
 785.5,
 15.5,
 3.0,
 38.0,
 178.0,
 88.0,
 3.0,
 3.0,
 8.0,
 145.5,
 78.0,
 3.0,
 3.0,
 8.0,
 3.0,
 8.0,
 18.0,
 13.0,
 3.0,
 28.0,
 98.0,
 3.0,
 1448.0,
 160.5,
 15.5,
 5.5,
 3.0,
 40.5,
 288.0,
 5.5,
 3.0,
 8.0,
 13.0,
 3.0,
 3.0,
 20.5,
 25.5,
 3.0,
 3.0,
 23.0,
 5.5,
 3.0,
 20.5,
 25.5,
 45.5,
 3.0,
 28.0,
 5.5,
 33.0,
 8.0,
 53.0,
 5.5,
 105.5,
 23.0,
 498.0,
 18.0,
 138.0,
 473.0,
 3.0,
 53.0,
 493.0,
 8.0,
 8.0,
 83.0,
 8.0,
 15.5,
 3.0,
 3.0,
 50.5,
 133.0,
 13.0,
 30.5,
 3.0,
 18.0,
 3.0,
 793.0,
 3.0,
 155.5,
 5.5,
 8.0,
 105.5,
 173.0,
 15.5,
 38.0,
 703.0,
 5.5,
 8.0,
 80.5,
 10.5,
 3.0,
 788.0,
 3.0,
 53.0,
 3.0,
 3.0,
 18.0,
 333.0,
 58.0,
 115.5,
 243.0,
 3.0,
 583.0,
 10.5,
 

In [136]:
projection1_train.shape

(999, 50)

In [137]:
sim_results, rank_results = find_ranking(projection1_train, projection2_train)

In [138]:
rank_results

[9.0,
 4.0,
 1.0,
 32.5,
 29.5,
 1.0,
 1.0,
 2.0,
 51.0,
 13.0,
 9.5,
 1.0,
 4.0,
 3.0,
 3.5,
 4.0,
 4.0,
 7.0,
 1.5,
 3.0,
 1.0,
 157.5,
 12.0,
 1.0,
 5.0,
 60.0,
 3.0,
 17.0,
 87.0,
 2.0,
 4.0,
 2.0,
 3.0,
 9.0,
 8.5,
 1.0,
 1.0,
 4.0,
 3.0,
 1.0,
 1.0,
 21.0,
 1.0,
 1.0,
 157.5,
 3.5,
 1.0,
 8.0,
 36.0,
 18.0,
 1.0,
 1.0,
 2.0,
 29.5,
 16.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 4.0,
 3.0,
 1.0,
 6.0,
 20.0,
 1.0,
 290.0,
 32.5,
 3.5,
 1.5,
 1.0,
 8.5,
 58.0,
 1.5,
 1.0,
 2.0,
 3.0,
 1.0,
 1.0,
 4.5,
 5.5,
 1.0,
 1.0,
 5.0,
 1.5,
 1.0,
 4.5,
 5.5,
 9.5,
 1.0,
 6.0,
 1.5,
 7.0,
 2.0,
 11.0,
 1.5,
 21.5,
 5.0,
 100.0,
 4.0,
 28.0,
 95.0,
 1.0,
 11.0,
 99.0,
 2.0,
 2.0,
 17.0,
 2.0,
 3.5,
 1.0,
 1.0,
 10.5,
 27.0,
 3.0,
 6.5,
 1.0,
 4.0,
 1.0,
 159.0,
 1.0,
 31.5,
 1.5,
 2.0,
 21.5,
 35.0,
 3.5,
 8.0,
 141.0,
 1.5,
 2.0,
 16.5,
 2.5,
 1.0,
 158.0,
 1.0,
 11.0,
 1.0,
 1.0,
 4.0,
 67.0,
 12.0,
 23.5,
 49.0,
 1.0,
 117.0,
 2.5,
 17.0,
 85.0,
 3.0,
 2.0,
 2.5,
 1.0,
 10.5,
 1.0,
 12.0,
 147.0,
 1

In [1]:
run main.py

/home/M2015eliu/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/gensim/utils.py:1015: UserWarning: Pattern library is not installed, lemmatization won't be available.
  warnings.warn("Pattern library is not installed, lemmatization won't be available.")
ERROR (theano.sandbox.cuda): ERROR: Not using GPU. Initialisation of device 2 failed:
initCnmem: cnmemInit call failed! Reason=CNMEM_STATUS_OUT_OF_MEMORY. numdev=1

Using gpu device 0: GeForce GTX TITAN X (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 4007)


NO Training. Load the existed model: weights/201611232246_e10_1k1k.p
Evaluate the model using fast estimation...
Finish preparing the data!
Finished embedding,start projecting...
Finish preparing the data!
Finished embedding,start projecting...


In [3]:
sim_results, rank_results = find_ranking(projection1_train, projection2_train)

In [4]:
rank_results

[9.0,
 4.0,
 1.0,
 32.5,
 29.5,
 1.0,
 1.0,
 2.0,
 51.0,
 13.0,
 9.5,
 1.0,
 4.0,
 3.0,
 3.5,
 4.0,
 4.0,
 7.0,
 1.5,
 3.0,
 1.0,
 157.5,
 12.0,
 1.0,
 5.0,
 60.0,
 3.0,
 17.0,
 87.0,
 2.0,
 4.0,
 2.0,
 3.0,
 9.0,
 8.5,
 1.0,
 1.0,
 4.0,
 3.0,
 1.0,
 1.0,
 21.0,
 1.0,
 1.0,
 157.5,
 3.5,
 1.0,
 8.0,
 36.0,
 18.0,
 1.0,
 1.0,
 2.0,
 29.5,
 16.0,
 1.0,
 1.0,
 2.0,
 1.0,
 2.0,
 4.0,
 3.0,
 1.0,
 6.0,
 20.0,
 1.0,
 290.0,
 32.5,
 3.5,
 1.5,
 1.0,
 8.5,
 58.0,
 1.5,
 1.0,
 2.0,
 3.0,
 1.0,
 1.0,
 4.5,
 5.5,
 1.0,
 1.0,
 5.0,
 1.5,
 1.0,
 4.5,
 5.5,
 9.5,
 1.0,
 6.0,
 1.5,
 7.0,
 2.0,
 11.0,
 1.5,
 21.5,
 5.0,
 100.0,
 4.0,
 28.0,
 95.0,
 1.0,
 11.0,
 99.0,
 2.0,
 2.0,
 17.0,
 2.0,
 3.5,
 1.0,
 1.0,
 10.5,
 27.0,
 3.0,
 6.5,
 1.0,
 4.0,
 1.0,
 159.0,
 1.0,
 31.5,
 1.5,
 2.0,
 21.5,
 35.0,
 3.5,
 8.0,
 141.0,
 1.5,
 2.0,
 16.5,
 2.5,
 1.0,
 158.0,
 1.0,
 11.0,
 1.0,
 1.0,
 4.0,
 67.0,
 12.0,
 23.5,
 49.0,
 1.0,
 117.0,
 2.5,
 17.0,
 85.0,
 3.0,
 2.0,
 2.5,
 1.0,
 10.5,
 1.0,
 12.0,
 147.0,
 1

In [5]:
	sim_results_train, rank_results_train = find_ranking(projection1_train, projection2_train)
	sim_results_test, rank_results_test = find_ranking(projection1_train, projection2_train)