In [3]:
df_train_1

en_article  \
0    u.s. commerce department seasonal adjust annua...   
1    chinese budget smartphone maker xiaomi plan se...   
2    samsung electronics co ltd fell more percent t...   
3    fiat deal gain full control chrysler group llc...   
4    fiat share jump thursday it strike deal gain f...   
5    u.s. treasuries price rise thursday benchmark ...   
6                       auction detail see 3-year note   
7    brent crude sink barrel thursday libya prepare...   
8    gauge u.s. factory activity hold 2-1/2-year hi...   
9    work massive panama canal extension project ma...   
10   increase december car sale france spain prompt...   
11   federal reserve provide liquidity foreign cent...   
12   new car sale spain rise percent year early car...   
13   south korean auto maker hyundai motor co kia m...   
14   u.s. manufacturing end year high note grow dec...   
15   oil price fell more thursday libya prepare res...   
16   freddie mac average u.s. mortgage rate percent...   
17   u.s. construction spending rise it high level ...   
18   russia world big oil producer raise output pos...   
19                                         morning fix   
20   premium italian spanish bond offer benchmark g...   
21   china yuan pull back slightly record high doll...   
22   italian carmaker fiat spa say wednesday it hav...   
23   brent crude rise barrel thursday decline oil s...   
24   china have approve more company list mainland ...   
25   janet yellen come step close final approval fe...   
26   libya hop resume oil production it large oilfi...   
27   italian carmaker fiat spa strike deal gain ful...   
28   number american file new claim unemployment be...   
29   britain top share index fell first trading day...   
..                                                 ...   
970  sometimes news be bad news j.c. penney co inc ...   
971  european central bank unexpected cut interest ...   
972  doji jpy sideline eur volatility ahead tonight...   
973  u.s. labor department report initial state job...   
974  president barack obama invited german chancell...   
975  european central bank leave interest rate unch...   
976  china will spend more km mile new railway line...   
977  european central bank leave interest rate unch...   
978  european central bank keep interest rate stead...   
979  european central bank keep interest rate stead...   
980  european central bank keep interest rate recor...   
981  european central bank leave interest rate unch...   
982  european central bank unexpected cut interest ...   
983  be result federal reserve purchase treasury th...   
984  european central bank leave interest rate unch...   
985  european central bank leave interest rate unch...   
986  european central bank leave interest rate unch...   
987  european central bank leave interest rate unch...   
988  daimler ag mercedes-benz unit saw vehicle sale...   
989  european central bank leave interest rate unch...   
990  european central bank keep interest rate stead...   
991  european central bank cut interest rate record...   
992  european central bank hold borrow rate thursda...   
993  european central bank hold borrow rate thursda...   
994  alcoa inc report massive quarterly loss thursd...   
995  european central bank cut interest rate record...   
996  european central bank unexpected cut interest ...   
997  thai stock rise thursday investor build positi...   
998  european central bank leave interest rate unch...   
999  european central bank leave interest rate unch...   

                                     transformation_en  \
0                       [5, 2, 9, 6, 6, 6, 6, 2, 6, 6]   
1    [2, 6, 2, 2, 2, 1, 2, 2, 5, 6, 2, 2, 2, 2, 10,...   
2    [2, 2, 2, 2, 5, 5, 5, 5, 2, 5, 6, 5, 5, 5, 6, ...   
3    [2, 1, 5, 1, 8, 2, 8, 10, 5, 2, 1, 5, 5, 5, 5,...   
4    [2, 1, 5, 5, 2, 8, 1, 5, 1, 8, 2, 8, 10, 7, 4,...   
5    [5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 10,...   
6                                      [1

In [36]:
a = pd.Series([int(n) for n in train_1[0][0].split()])
d = a.value_counts().to_dict()
[d[x] if x in d.keys() else 0 for x in range(1,11)]

[0, 2, 6, 3, 5, 0, 8, 4, 5, 6]

In [39]:
train_1[0][0]

'2 3 10 7 3 10 8 8 9 8 9 3 10 7 5 4 7 7 2 4 9 3 5 10 5 4 9 10 9 3 10 7 5 3 5 7 8 7 7'

In [51]:
def freq_count(appearance):
	a = pd.Series([int(n) for n in appearance.split()])
	d = a.value_counts().to_dict()
	r = [d[x] if x in d.keys() else 0 for x in range(1,11)]
	return r

In [54]:
df_train_1['xa_c'] = df_train_1['xa'].apply(freq_count)
df_train_1['xb_c'] = df_train_1['xb'].apply(freq_count)
df_train_1['f'] = 

In [64]:
df_train_1

en_article  \
0    u.s. commerce department seasonal adjust annua...   
1    chinese budget smartphone maker xiaomi plan se...   
2    samsung electronics co ltd fell more percent t...   
3    fiat deal gain full control chrysler group llc...   
4    fiat share jump thursday it strike deal gain f...   
5    u.s. treasuries price rise thursday benchmark ...   
6                       auction detail see 3-year note   
7    brent crude sink barrel thursday libya prepare...   
8    gauge u.s. factory activity hold 2-1/2-year hi...   
9    work massive panama canal extension project ma...   
10   increase december car sale france spain prompt...   
11   federal reserve provide liquidity foreign cent...   
12   new car sale spain rise percent year early car...   
13   south korean auto maker hyundai motor co kia m...   
14   u.s. manufacturing end year high note grow dec...   
15   oil price fell more thursday libya prepare res...   
16   freddie mac average u.s. mortgage rate percent...   
17   u.s. construction spending rise it high level ...   
18   russia world big oil producer raise output pos...   
19                                         morning fix   
20   premium italian spanish bond offer benchmark g...   
21   china yuan pull back slightly record high doll...   
22   italian carmaker fiat spa say wednesday it hav...   
23   brent crude rise barrel thursday decline oil s...   
24   china have approve more company list mainland ...   
25   janet yellen come step close final approval fe...   
26   libya hop resume oil production it large oilfi...   
27   italian carmaker fiat spa strike deal gain ful...   
28   number american file new claim unemployment be...   
29   britain top share index fell first trading day...   
..                                                 ...   
970  sometimes news be bad news j.c. penney co inc ...   
971  european central bank unexpected cut interest ...   
972  doji jpy sideline eur volatility ahead tonight...   
973  u.s. labor department report initial state job...   
974  president barack obama invited german chancell...   
975  european central bank leave interest rate unch...   
976  china will spend more km mile new railway line...   
977  european central bank leave interest rate unch...   
978  european central bank keep interest rate stead...   
979  european central bank keep interest rate stead...   
980  european central bank keep interest rate recor...   
981  european central bank leave interest rate unch...   
982  european central bank unexpected cut interest ...   
983  be result federal reserve purchase treasury th...   
984  european central bank leave interest rate unch...   
985  european central bank leave interest rate unch...   
986  european central bank leave interest rate unch...   
987  european central bank leave interest rate unch...   
988  daimler ag mercedes-benz unit saw vehicle sale...   
989  european central bank leave interest rate unch...   
990  european central bank keep interest rate stead...   
991  european central bank cut interest rate record...   
992  european central bank hold borrow rate thursda...   
993  european central bank hold borrow rate thursda...   
994  alcoa inc report massive quarterly loss thursd...   
995  european central bank cut interest rate record...   
996  european central bank unexpected cut interest ...   
997  thai stock rise thursday investor build positi...   
998  european central bank leave interest rate unch...   
999  european central bank leave interest rate unch...   

                                     transformation_en  \
0                       [5, 2, 9, 6, 6, 6, 6, 2, 6, 6]   
1    [2, 6, 2, 2, 2, 1, 2, 2, 5, 6, 2, 2, 2, 2, 10,...   
2    [2, 2, 2, 2, 5, 5, 5, 5, 2, 5, 6, 5, 5, 5, 6, ...   
3    [2, 1, 5, 1, 8, 2, 8, 10, 5, 2, 1, 5, 5, 5, 5,...   
4    [2, 1, 5, 5, 2, 8, 1, 5, 1, 8, 2, 8, 10, 7, 4,...   
5    [5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 10,...   
6                                      [1

In [50]:
train_1[0][0]

'2 3 10 7 3 10 8 8 9 8 9 3 10 7 5 4 7 7 2 4 9 3 5 10 5 4 9 10 9 3 10 7 5 3 5 7 8 7 7'

In [63]:
	df_train_1['xa_c'] = df_train_1['xa'].apply(freq_count)
	df_train_1['xb_c'] = df_train_1['xb'].apply(freq_count)
	df_train_1['xb_c_wrong'] = df_train_1['xb_wrong'].apply(freq_count)

	df_train_1['feature'] = df_train_1['xa_c'] + df_train_1['xb_c']
	df_train_1['feature_wrong'] = df_train_1['xa_c'] + df_train_1['xb_c_wrong']

In [58]:
df_train_1['xa_c'][0]

[0, 2, 6, 3, 5, 0, 8, 4, 5, 6]

In [66]:
df_train_1.iloc[0]

en_article           u.s. commerce department seasonal adjust annua...
transformation_en                       [5, 2, 9, 6, 6, 6, 6, 2, 6, 6]
jp_article           米 商務省 発表 する 建設 支出 以下 とおり 季節調整 年率 総 建設 支出 民間 部門...
transformation_jp    [2, 3, 10, 7, 3, 10, 8, 8, 9, 8, 9, 3, 10, 7, ...
similarity                                                           5
dis_similarity                                                       1
en2jp_projection     [1, 8, 2, 3, 9, 7, 2, 9, 7, 2, 9, 7, 2, 9, 7, ...
xa                   2 3 10 7 3 10 8 8 9 8 9 3 10 7 5 4 7 7 2 4 9 3...
xb                     1 8 2 3 9 7 2 9 7 2 9 7 2 9 7 2 8 2 9 7 2 9 7 2
xb_wrong             10 3 10 3 1 10 3 9 7 2 9 7 2 1 1 10 3 6 6 6 8 ...
xa_c                                    [0, 2, 6, 3, 5, 0, 8, 4, 5, 6]
xb_c                                    [1, 8, 1, 0, 0, 0, 6, 2, 6, 0]
feature              [0, 2, 6, 3, 5, 0, 8, 4, 5, 6, 1, 8, 1, 0, 0, ...
xb_c_wrong                  [52, 86, 100, 63, 22, 43, 33, 53, 33, 158]
featur

In [65]:
df_train_1

en_article  \
0    u.s. commerce department seasonal adjust annua...   
1    chinese budget smartphone maker xiaomi plan se...   
2    samsung electronics co ltd fell more percent t...   
3    fiat deal gain full control chrysler group llc...   
4    fiat share jump thursday it strike deal gain f...   
5    u.s. treasuries price rise thursday benchmark ...   
6                       auction detail see 3-year note   
7    brent crude sink barrel thursday libya prepare...   
8    gauge u.s. factory activity hold 2-1/2-year hi...   
9    work massive panama canal extension project ma...   
10   increase december car sale france spain prompt...   
11   federal reserve provide liquidity foreign cent...   
12   new car sale spain rise percent year early car...   
13   south korean auto maker hyundai motor co kia m...   
14   u.s. manufacturing end year high note grow dec...   
15   oil price fell more thursday libya prepare res...   
16   freddie mac average u.s. mortgage rate percent...   
17   u.s. construction spending rise it high level ...   
18   russia world big oil producer raise output pos...   
19                                         morning fix   
20   premium italian spanish bond offer benchmark g...   
21   china yuan pull back slightly record high doll...   
22   italian carmaker fiat spa say wednesday it hav...   
23   brent crude rise barrel thursday decline oil s...   
24   china have approve more company list mainland ...   
25   janet yellen come step close final approval fe...   
26   libya hop resume oil production it large oilfi...   
27   italian carmaker fiat spa strike deal gain ful...   
28   number american file new claim unemployment be...   
29   britain top share index fell first trading day...   
..                                                 ...   
970  sometimes news be bad news j.c. penney co inc ...   
971  european central bank unexpected cut interest ...   
972  doji jpy sideline eur volatility ahead tonight...   
973  u.s. labor department report initial state job...   
974  president barack obama invited german chancell...   
975  european central bank leave interest rate unch...   
976  china will spend more km mile new railway line...   
977  european central bank leave interest rate unch...   
978  european central bank keep interest rate stead...   
979  european central bank keep interest rate stead...   
980  european central bank keep interest rate recor...   
981  european central bank leave interest rate unch...   
982  european central bank unexpected cut interest ...   
983  be result federal reserve purchase treasury th...   
984  european central bank leave interest rate unch...   
985  european central bank leave interest rate unch...   
986  european central bank leave interest rate unch...   
987  european central bank leave interest rate unch...   
988  daimler ag mercedes-benz unit saw vehicle sale...   
989  european central bank leave interest rate unch...   
990  european central bank keep interest rate stead...   
991  european central bank cut interest rate record...   
992  european central bank hold borrow rate thursda...   
993  european central bank hold borrow rate thursda...   
994  alcoa inc report massive quarterly loss thursd...   
995  european central bank cut interest rate record...   
996  european central bank unexpected cut interest ...   
997  thai stock rise thursday investor build positi...   
998  european central bank leave interest rate unch...   
999  european central bank leave interest rate unch...   

                                     transformation_en  \
0                       [5, 2, 9, 6, 6, 6, 6, 2, 6, 6]   
1    [2, 6, 2, 2, 2, 1, 2, 2, 5, 6, 2, 2, 2, 2, 10,...   
2    [2, 2, 2, 2, 5, 5, 5, 5, 2, 5, 6, 5, 5, 5, 6, ...   
3    [2, 1, 5, 1, 8, 2, 8, 10, 5, 2, 1, 5, 5, 5, 5,...   
4    [2, 1, 5, 5, 2, 8, 1, 5, 1, 8, 2, 8, 10, 7, 4,...   
5    [5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5, 6, 10,...   
6                                      [1

In [70]:
train_right = df_train_1[['feature','similarity']].values.tolist()
train_wrong = df_train_1[['feature_wrong','dis_similarity']].values.tolist()

In [76]:
train_right[0]

[[0, 2, 6, 3, 5, 0, 8, 4, 5, 6, 1, 8, 1, 0, 0, 0, 6, 2, 6, 0], 5.0]

In [74]:
train_wrong[0]

[[0, 2, 6, 3, 5, 0, 8, 4, 5, 6, 52, 86, 100, 63, 22, 43, 33, 53, 33, 158], 1.0]

In [ ]:
train_right = df_train_1[['feature','similarity']].values.tolist()
train_wrong = df_train_1[['feature_wrong','dis_similarity']].values.tolist()	
clf = linear_model.LogisticRegression(C=1.0, penalty='l1', tol=1e-6)

In [83]:
X = [i[0] for i in (train_right + train_wrong)]
np.array(X).shape

(1998, 20)

In [85]:
X[1]

[0, 3, 7, 6, 10, 1, 18, 9, 4, 2, 25, 109, 16, 13, 0, 9, 20, 89, 20, 22]

In [87]:
y = [i[1] for i in (train_right + train_wrong)]
np.array(y).shape

(1998,)

In [119]:
from sklearn import linear_model
clf = linear_model.LogisticRegression(C=1.0, penalty='l1', tol=1e-6)
clf.fit(X_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=1e-06,
          verbose=0, warm_start=False)

In [128]:
clf.score(X_train, y_train)

0.5

In [129]:
clf.predict(X_train)

array([ 0.,  0.,  0., ...,  0.,  0.,  0.])

In [118]:
	X_train = np.array([i[0] for i in (train_right + train_wrong)])
	y_train = (np.array([i[1] for i in (train_right + train_wrong)])-1)/4

In [133]:
X_train.shape

(1998, 20)

In [166]:
clf.fit(X_train,y_test)

NameError: name 'clf2' is not defined

In [215]:
y = np.array([i[1] for i in (train_right + train_wrong)])

In [152]:
sum(clf.predict(X))

1998.0

In [156]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler

digits = datasets.load_digits()

X, y = digits.data, digits.target
X = StandardScaler().fit_transform(X)

# classify small against large digits
y = (y > 4).astype(np.int)


In [212]:
clf.fit(X, y)

ValueError: Found arrays with inconsistent numbers of samples: [1797 1998]

In [158]:
clf.score(X,y)

0.91040623260990539

In [159]:
	df_test_1['xa_c'] = df_test_1['xa'].apply(freq_count)
	df_test_1['xb_c'] = df_test_1['xb'].apply(freq_count)
	df_test_1['xb_c_wrong'] = df_test_1['xb_wrong'].apply(freq_count)

	df_test_1['feature'] = df_test_1['xa_c'] + df_test_1['xb_c']
	df_test_1['feature_wrong'] = df_test_1['xa_c'] + df_test_1['xb_c_wrong']

	test_right = df_test_1[['feature','similarity']].values.tolist()
	test_wrong = df_test_1[['feature_wrong','dis_similarity']].values.tolist()

	X_test = np.array([i[0] for i in (test_right + test_wrong)])
	y_test = (np.array([i[1] for i in (test_right + test_wrong)])-1)/4

In [167]:
clf.fit(X_train, y_train)
clf.score(X_test, y_test)

0.5

In [182]:
pd.Series(X[0]).describe()

count    64.000000
mean     -0.015717
std       0.766832
min      -1.736664
25%      -0.377509
50%      -0.034406
75%       0.493735
max       1.905963
dtype: float64

In [183]:
X = StandardScaler().fit_transform(X_train)

/home/M2015eliu/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
/home/M2015eliu/.pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/sklearn/utils/validation.py:420: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [222]:
X

array([[-0.91038948, -0.72159664, -0.58937845, ..., -1.01986415,
        -0.93512196, -1.08217682],
       [-0.91038948, -0.623465  , -0.51083135, ...,  0.80549526,
        -0.22467513, -0.69292472],
       [-0.68037454, -0.32907007,  0.43173387, ...,  0.05017412,
         1.24696474, -0.7813911 ],
       ..., 
       [-0.45035959, -0.03467514, -0.19664294, ..., -0.32748644,
         0.13054829,  1.43026859],
       [ 2.30981974,  1.63356277,  2.00267591, ..., -1.06182643,
        -1.23959918, -1.08217682],
       [ 0.0096703 , -0.32907007, -0.74647266, ..., -0.4533733 ,
        -1.03661437, -0.44521883]])

In [211]:
X_train[1]

array([  0,   3,   7,   6,  10,   1,  18,   9,   4,   2,  25, 109,  16,
        13,   0,   9,  20,  89,  20,  22])

In [229]:
clf.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l1', random_state=None, solver='liblinear', tol=1e-06,
          verbose=0, warm_start=False)

In [235]:
clf.predict(X)

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [236]:
X_train

array([[  0,   2,   6, ...,   2,   6,   0],
       [  0,   3,   7, ...,  89,  20,  22],
       [  1,   6,  19, ...,  53,  49,  17],
       ..., 
       [  2,   9,  11, ...,  35,  27, 142],
       [ 14,  26,  39, ...,   0,   0,   0],
       [  4,   6,   4, ...,  29,   4,  36]])